const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_REQUIRED: "TOKEN_REQUIRED",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EXISTS: "USER_EXISTS",
  USER_INACTIVE: "USER_INACTIVE",
  USER_BANNED: "USER_BANNED",
  DB_ERROR: "DB_ERROR",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
};

module.exports = ERROR_CODES;
